enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: true
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  'user/themes/quark/images/logo/Ara Landscape Logo_White.png':
    name: 'Ara Landscape Logo_White.png'
    full_path: 'Ara Landscape Logo_White.png'
    type: image/png
    size: 19359
    path: 'user/themes/quark/images/logo/Ara Landscape Logo_White.png'
custom_logo_mobile:
  'user/themes/quark/images/logo/Ara Primary Logo_White.png':
    name: 'Ara Primary Logo_White.png'
    full_path: 'Ara Primary Logo_White.png'
    type: image/png
    size: 55670
    path: 'user/themes/quark/images/logo/Ara Primary Logo_White.png'
